# helm upgrade --install crud-db-postgresql -f helm\pg\values.yaml oci://registry-1.docker.io/bitnamicharts/postgresql
global:
  postgresql:
    auth:
      postgresPassword: "pg"
      username: "crudapi"
      password: "a2dvxX32fds"
      database: "crudapi"

metrics:
  enabled: true