---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-6"
  name: {{ .Values.fullnameOverride }}-cm
data:
    {{- toYaml .Values.config  | nindent 4 }}
---
