apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dz2
  labels:
    app.kubernetes.io/name: nginx-dz2
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-dz2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-dz2
    spec:
      containers:
      - name: nginx-dz2
        image: zakaryanla/nginx-dz2:2.0
        ports:
        - containerPort: 8000
        startupProbe:
          httpGet:
            path: /health/
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 1
          timeoutSeconds: 5
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 30
        readinessProbe:
          httpGet:
            path: /health/
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 2
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health/
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 5
