apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "crud-api-dz4.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "crud-api-dz4.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "crud-api-dz4.fullname" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "crud-api-dz4.fullname" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          envFrom:
            - configMapRef:
                name: {{ include "crud-api-dz4.fullname" . }}-cm
            - secretRef:
                name: {{ include "crud-api-dz4.fullname" . }}-secret
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
