---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-4"
  name: {{ include "crud-api-dz4.fullname" . }}-secret
type: Opaque
data:
    PGUSER: {{ .Values.secrets.PGUSER | b64enc | quote }}
    PGPASSWORD: {{ .Values.secrets.PGPASSWORD | b64enc | quote }}
---
