# helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx/
# helm upgrade --install nginx ingress-nginx/ingress-nginx --namespace m -f helm\nginx\values.yaml
controller:
  kind: DaemonSet
  
  reportNodeInternalIp: true

  hostPort:
    enabled: true
    ports:
      http: 80
      https: 443

  service:
    type: NodePort

  metrics:
    enabled: true
    service:
      annotations: 
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
        prometheus.io/path: "/metrics"

  config:
    proxy-buffer-size: "8k"