# helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
# helm upgrade --install prometheus prometheus-community/prometheus --version 25.26.0 ‐‐namespace pm -f helm\prometheus\values.yaml
server:
  ingress:
    enabled: true
    hosts: 
    - arch-pm.homework
    ingressClassName: nginx
prometheus-pushgateway:
  enabled: false
alertmanager:
  enabled: false
