{
 "title": "Flask Web App",
 "description": "Dashboard for official Prometheus Python Client's metrics",
 "tags": [
  "flask",
  "app",
  "web",
  "python"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "3s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "deployment",
    "query": {
     "query": "label_values(flask_exporter_info,app_kubernetes_io_name)"
    }
   },
   {
    "name": "pod",
    "label": "Pod name",
    "query": {
     "query": "label_values(flask_exporter_info{app_kubernetes_io_name=\"$deployment\"},pod)"
    }
   },
   {
    "name": "method",
    "label": "HTTP Method",
    "query": {
     "query": "label_values(flask_http_request_duration_seconds_bucket,method)"
    }
   },
   { "name": "percentile", "label": "Percentile", "query": "100,99,95,50" },
   {
    "name": "error_code",
    "label": "Status code 4xx or 5xx",
    "query": {
     "query": "label_values(flask_http_request_total,status)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Приложение", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS",
   "type": "timeseries",
   "description": "Requests per second ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total{pod=~\"$pod\", app_kubernetes_io_name=\"$deployment\"}[$interval])) by (app_kubernetes_io_name,method)",
     "legendFormat": "{{ app_kubernetes_io_name}} - {{ method }}"
    }
   ]
  },
  {
   "title": "Request Latency, s",
   "type": "timeseries",
   "description": "Latency per pod, endpoint and method",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_sum{app_kubernetes_io_name=\"$deployment\",pod=~\"$pod\", method=~\"$method\"}[$interval])) by (app_kubernetes_io_name, method) / \r\nsum(rate(flask_http_request_duration_seconds_count{app_kubernetes_io_name=\"$deployment\",pod=~\"$pod\", method=~\"$method\"}[$interval])) by (app_kubernetes_io_name, method) ",
     "legendFormat": "{{ app_kubernetes_io_name}} {{ method }}"
    }
   ]
  },
  {
   "title": "Latency within which $percentile% of requests served",
   "type": "timeseries",
   "description": "See more:\nhttps://prometheus.io/docs/practices/histograms/",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile / 100, sum(rate(flask_http_request_duration_seconds_bucket{pod=~\"$pod\", app_kubernetes_io_name=\"$deployment\"}[$interval])) by (le, method, app_kubernetes_io_name ))",
     "legendFormat": "{{ app_kubernetes_io_name }} {{method }} latency"
    }
   ]
  },
  {
   "title": "4xx, 5xx errors per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total{status=~\"4..|5..\", pod=~\"$pod\", method=~\"$method\", app_kubernetes_io_name=\"$deployment\"}[$interval])) by (method,status, app_kubernetes_io_name)",
     "legendFormat": "{{ app_kubernetes_io_name }} {{ method }} {{ status }} Errors per second"
    }
   ]
  },
  {
   "title": "4xx, 5xx errors count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(flask_http_request_total{status=~\"$error_code\", pod=~\"$pod\", method=~\"$method\", app_kubernetes_io_name=\"$deployment\"}) by (app_kubernetes_io_name, method)",
     "legendFormat": "{{ app_kubernetes_io_name }} {{ method}} {{ status}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{pod=~\"$pod\",app_kubernetes_io_name=\"$deployment\"}[$interval])",
     "legendFormat": "{{ pod }} cpu"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{pod=~\"$pod\", app_kubernetes_io_name=\"$deployment\"}",
     "legendFormat": "{{pod}} memory"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(process_open_fds{pod=~\"$pod\",app_kubernetes_io_name=\"$deployment\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}