# helm upgrade --install notifications helm\notifications -n billing
fullnameOverride: "notifications"

replicaCount: 1

image:
  repository: zakaryanla/notifications
  pullPolicy: Always
  tag: "1.0"

metrics:
  enabled: true
  path: /metrics
  port: "8000"

imagePullSecrets: []

config:
  PGHOST: '10.105.78.67'
  PGPORT: '5432'
  PGDATABASE: crudapi
  GUNICORN_PROCESSES: "3"

  RMQ_HOSTNAME: 10.104.51.247
  RMQ_LOGIN: "notifications"
  RMQ_PASS: "BNL54CXxc94"

  KEYCLOAK_URL: http://10.104.253.37/
  KEYCLOAK_USER: crud
  KEYCLOAK_PASS: sadsfASdcsdf
  KEYCLOAK_REALM: app
  KEYCLOAK_CLIENT_ID: crud
  KEYCLOAK_CLIENT_SECRET: Y9BkXRzSKdKbVqaC07nBUgJpOJbVZu4t
  
secrets:
  PGUSER: crudapi
  PGPASSWORD: a2dvxX32fds

migrate:
  enabled: true
  command: cd db && pgmigrate -t latest migrate -m notifications

resources:
  limits:
    cpu: "1"
    memory: "512Mi"
  requests:
    cpu: 100m
    memory: "128Mi" 

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  className: nginx
  annotations: 
    nginx.ingress.kubernetes.io/auth-url: "http://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "http://$host/oauth2/start?rd=http://$host/api/v1/billing/check"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-Auth-Request-User, X-Auth-Request-Preferred-Username, x-auth-request-email, authorization"
    nginx.ingress.kubernetes.io/auth-request-set: "$id $upstream_http_x_auth_request_preferred_username"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"

  hosts:
    - host: "arch.homework"
      paths:
        - path: /api/v1/notifications
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# readinessProbe:
#   httpGet:
#     path: /api/v1/user/1
#     port: 5000
#     scheme: HTTP
#   initialDelaySeconds: 10
#   timeoutSeconds: 10
#   periodSeconds: 30
#   successThreshold: 2
#   failureThreshold: 4
# livenessProbe:
#   httpGet:
#     path: /api/v1/user/1
#     port: 5000
#     scheme: HTTP
#   initialDelaySeconds: 10
#   timeoutSeconds: 10
#   periodSeconds: 30
#   successThreshold: 1
#   failureThreshold: 8
