apiVersion: v1
kind: Service
metadata:
  name: {{ include "crud-api-dz4.fullname" . }}-service
  labels:
    {{- include "crud-api-dz4.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "crud-api-dz4.fullname" . }}
