apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-dz2-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /health/
spec:
  ingressClassName: nginx
  rules:
  - host: "arch.homework"
    http:
      paths:
      - path: /otusapp/lavrenti/health
        pathType: Prefix
        backend:
          service:
            name: nginx-dz2-service
            port:
              number: 8000