apiVersion: v1
kind: Service
metadata:
  name: nginx-dz2-service2
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nginx-dz2
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000