---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-6"
  name: {{ .Values.fullnameOverride }}-secret
type: Opaque
data:
  {{- $v := .Values.secrets }}
  {{- range $key, $val := $v }}
  {{ $key | indent 4 }}: {{ $val | b64enc }}
  {{- end}}
---
