# helm upgrade --install subscriptions helm\subscriptions -n lib
fullnameOverride: "subscriptions"

replicaCount: 1

image:
  repository: zakaryanla/subscriptions
  pullPolicy: Always
  tag: "v1.0"

metrics:
  enabled: true
  path: /metrics
  port: "8000"

imagePullSecrets: []

config:
  PGHOST: '10.99.220.149'
  PGPORT: '5432'
  PGDATABASE: library
  GUNICORN_PROCESSES: "3"

  RMQ_HOSTNAME: 10.111.183.32
  RMQ_LOGIN: "subscriptions"
  RMQ_PASS: "vcxDsxcv23xz"

  KEYCLOAK_URL: http://10.110.39.232/
  KEYCLOAK_USER: adminlib
  KEYCLOAK_PASS: sadsfASdcsdf
  KEYCLOAK_REALM: app
  KEYCLOAK_CLIENT_ID: Adminlib
  KEYCLOAK_CLIENT_SECRET: wZqn7HCVUy1RH8lgMywqddVPBBjV0XkT

  SMTP_PORT: "465"
  SMTP_SERVER: smtp.yandex.ru
  SMTP_SENDER: zakaryanla@yandex.ru
  SMTP_PASS: 

secrets:
  PGUSER: library
  PGPASSWORD: a2dvxX32fds

migrate:
  enabled: true
  command: cd db && pgmigrate -t latest migrate -m nf

resources:
  limits:
    cpu: "1"
    memory: "512Mi"
  requests:
    cpu: 100m
    memory: "128Mi" 

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  className: nginx
  annotations: 
    nginx.ingress.kubernetes.io/auth-url: "http://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "http://$host/oauth2/start?rd=http://$host/api/v1"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-Auth-Request-User, X-Auth-Request-Preferred-Username, x-auth-request-email, authorization"
    nginx.ingress.kubernetes.io/auth-request-set: "$id $upstream_http_x_auth_request_preferred_username"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"

  hosts:
    - host: "arch.homework"
      paths:
        - path: /api/v1/subscriptions
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

livenessProbe:
  httpGet:
    path: /health
    port: 5000
    scheme: HTTP
  initialDelaySeconds: 10
  timeoutSeconds: 10
  periodSeconds: 30
  successThreshold: 1
  failureThreshold: 8
